% define female and male
female(mum).
female(elizabeth).
female(margaret).
female(spencer).
female(diana).
female(anne).
female(sarah).
female(sophie).
female(zara).
female(beatrice).
female(eugenie).
female(louise).
male(george).
male(philip).
male(kydd).
male(charles).
male(mark).
male(andrew).
male(edward).
male(william).
male(harry).
male(peter).
male(james).
% define couple
couple(george,mum).
couple(elizabeth,philip).
couple(spencer,kydd).
couple(diana,charles).
couple(anne,mark).
couple(andrew,sarah).
couple(edward,sophie).
couple(mum,george).
couple(philip,elizabeth).
couple(kydd,spencer).
couple(charles,diana).
couple(mark,anne).
couple(sarah,andrew).
couple(sophie,edward).
% define parents parent(X,Y)::= X is Y's parent
parent(george,elizabeth).
parent(mum,elizabeth).
parent(george,margaret).
parent(mum,margaret).
parent(spencer,diana).
parent(kydd,diana).
parent(elizabeth,charles).
parent(philip,charles).
parent(elizabeth,anne).
parent(philip,anne).
parent(elizabeth,andrew).
parent(philip,andrew).
parent(elizabeth,edward).
parent(philip,edward).
parent(diana,william).
parent(charles,william).
parent(diana,harry).
parent(charles,harry).
parent(anne,peter).
parent(mark,peter).
parent(anne,zara).
parent(mark,zara).
parent(andrew,beatrice).
parent(sarah,beatrice).
parent(andrew,eugenie).
parent(sarah,eugenie).
parent(edward,louise).
parent(sophie,louise).
parent(edward,james).
parent(sophie,james).

% define others
sibling(X,Y):-parent(Z,X),parent(Z,Y),X\=Y.
grandChild(X,Y):-parent(Z,X),parent(Y,Z).
greatGrandparent(X,Y):-grandChild(Y,Z),parent(X,Z).
ancestor(X,Y):-parent(X,Y).
ancestor(X,Y):-parent(X,Z),ancestor(Z,Y).
brother(X,Y):-male(X),sibling(X,Y).
sister(X,Y):-female(X),sibling(X,Y).
duaghter(X,Y):-parent(X,Y),female(X).
son(X,Y):-parent(X,Y),male(X).
firstCousin(X,Y):-parent(P1,X),parent(P2,Y),sibling(P1,P2).
brotherInLaw(X,Y):-couple(X,M),brother(Y,M).
sisterInLaw(X,Y):-couple(X,M),sister(Y,M).
aunt(X,Y):-parent(P,Y),(sister(X,P);sisterInLaw(X,P)).
uncle(X,Y):-parent(P,Y),(brother(X,P);brotherInLaw(X,P)).

distance(X,X,0).
distance(X,Y,N):-T is N - 1,parent(X,Z),distance(Z,Y,T).
mthCousinNremoved(X,Y,M,N):-distance(Z,X,M+1),distance(Z,R,M+1),distance(R,Y,N),X\=Y,\+sibling(X,R),X\=R.